---
apiVersion: v1
kind: Service
metadata:
  name: skosmos-store
spec:
  selector:
    app: skosmos-store
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
