---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skosmos
  labels:
    app: skosmos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skosmos
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: skosmos
      annotations:
        prometheus.io/scrape: 'false'
    spec:
      containers:
        - name: skosmos
          image: skosmos
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            tcpSocket: { port: 8080 }
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            tcpSocket: { port: 8080 }
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 6
          resources:
            requests:
              cpu: 100m
              memory: 500Mi