---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skosmos
  labels:
    app: skosmos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skosmos
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: skosmos
      annotations:
        prometheus.io/scrape: 'false'
    spec:
      containers:
        - name: skosmos
          image: skosmos
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 500Mi