---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skosmos
  labels:
    app: skosmos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skosmos
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: skosmos
      annotations:
        prometheus.io/scrape: 'false'
    spec:
      containers:
        - name: skosmos
          image: skosmos
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: 8080
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
            initialDelaySeconds: 20
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ready
              port: 8080
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
            initialDelaySeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 500Mi