name: Deploy to demo
permissions:
    contents: read
    packages: write
on:
  push:
    branches:
      - main

jobs:

  build:
    name: Build images
    strategy:
      matrix:
        app_name: [Skosmos,skosmos-store]
    uses: Informasjonsforvaltning/workflows/.github/workflows/build-push.yaml@main
    with:
      app_name: ${{ matrix.app_name }}
      monorepo_app: true
      environment: staging
      gh_environment: staging
      build_env: true
      build_env_name: BINARY
      build_env_value: ${{ matrix.app_name }}
      dockerfile: apps/${{ matrix.app_name }}.Dockerfile
      submodule: true
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy images to demo environment
    needs: [build]
    strategy:
      matrix:
        app_name: [skosmos,skosmos-store]
    uses: Informasjonsforvaltning/workflows/.github/workflows/kustomize-deploy.yaml@main
    with:
      app_name: ${{ matrix.app_name }}
      environment: demo
      cluster: digdir-fdk-dev
      monorepo_app: true
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DIGDIR_FDK_AUTODEPLOY: ${{ secrets.DIGDIR_FDK_DEV_AUTODEPLOY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
