name: Deploy to staging
permissions:
    contents: read
    packages: write
on:
  pull_request:
    types: [ready_for_review, opened, reopened, synchronize]
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

jobs:

  build:
    name: Build images
    if: ${{ github.actor != 'dependabot[bot]' && github.event.pull_request.draft == false }}
    strategy:
      matrix:
        app_name: [Skosmos]
    uses: Informasjonsforvaltning/workflows/.github/workflows/build-push.yaml@main
    with:
      app_name: ${{ matrix.appname }}
      monorepo_app: true
      environment: staging
      gh_environment: staging
      build_env: true
      build_env_name: BINARY
      build_env_value: ${{ matrix.appname }}
      cache_path: ./dist
      dockerfile: apps/${{ matrix.appname }}/dockerfiles/Dockerfile.ubuntu
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy images to staging environment
    if: github.event.pull_request.draft == false
    needs: [build]
    uses: Informasjonsforvaltning/workflows/.github/workflows/kustomize-deploy.yaml@main
    with:
      app_name: skosmos-config
      environment: staging
      cluster: digdir-fdk-dev
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DIGDIR_FDK_AUTODEPLOY: ${{ secrets.DIGDIR_FDK_DEV_AUTODEPLOY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
